repos:
  # Format .py files with Black
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11
        files: "\\.py$"

  # Lint .py files with Ruff (and auto-fix where safe)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix]
        files: "\\.py$"

  # Notebooks via nbQA
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==24.4.2]
        files: "\\.ipynb$"
      - id: nbqa-ruff
        additional_dependencies: [ruff==0.6.9]
        args: [--fix]
        files: "\\.ipynb$"
